// <auto-generated>
// Generated by tools/codegen/generate_models.py from "Metron Comicbook Database.yaml".
// Do not edit by hand -- re-run the script instead.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Metron.Api.Http;

namespace Metron.Api.Filters;

public sealed class ArcFilter
{
    /// <summary>Comic Vine ID</summary>
    [QueryParameter("cv_id")]
    public int? CvId { get; set; }

    /// <summary>Grand Comics Database ID</summary>
    [QueryParameter("gcd_id")]
    public int? GcdId { get; set; }

    /// <summary>Greater than Modified DateTime</summary>
    [QueryParameter("modified_gt")]
    public DateTimeOffset? ModifiedGt { get; set; }

    [QueryParameter("name")]
    public string? Name { get; set; }

    /// <summary>A page number within the paginated result set.</summary>
    [QueryParameter("page")]
    public int? Page { get; set; }
}
