// <auto-generated>
// Generated by tools/codegen/generate_models.py from "Metron Comicbook Database.yaml".
// Do not edit by hand -- re-run the script instead.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Metron.Api.Http;

namespace Metron.Api.Filters;

public sealed class CollectionFilter
{
    /// <summary>Format of the comic (print, digital, or both)</summary>
    [QueryParameter("book_format")]
    public string? BookFormat { get; set; }

    [QueryParameter("date_read")]
    public DateOnly? DateRead { get; set; }

    [QueryParameter("date_read_gt")]
    public DateOnly? DateReadGt { get; set; }

    [QueryParameter("date_read_gte")]
    public DateOnly? DateReadGte { get; set; }

    [QueryParameter("date_read_lt")]
    public DateOnly? DateReadLt { get; set; }

    [QueryParameter("date_read_lte")]
    public DateOnly? DateReadLte { get; set; }

    /// <summary>Comic book grade (CGC scale)</summary>
    [QueryParameter("grade")]
    public double? Grade { get; set; }

    /// <summary>Professional grading company (leave blank for user-assessed grade)</summary>
    [QueryParameter("grading_company")]
    public string? GradingCompany { get; set; }

    [QueryParameter("is_read")]
    public bool? IsRead { get; set; }

    [QueryParameter("issue__series")]
    public int? IssueSeries { get; set; }

    /// <summary>Greater than Modified DateTime</summary>
    [QueryParameter("modified_gt")]
    public DateTimeOffset? ModifiedGt { get; set; }

    /// <summary>A page number within the paginated result set.</summary>
    [QueryParameter("page")]
    public int? Page { get; set; }

    [QueryParameter("purchase_date")]
    public DateOnly? PurchaseDate { get; set; }

    [QueryParameter("purchase_date_gt")]
    public DateOnly? PurchaseDateGt { get; set; }

    [QueryParameter("purchase_date_gte")]
    public DateOnly? PurchaseDateGte { get; set; }

    [QueryParameter("purchase_date_lt")]
    public DateOnly? PurchaseDateLt { get; set; }

    [QueryParameter("purchase_date_lte")]
    public DateOnly? PurchaseDateLte { get; set; }

    [QueryParameter("purchase_store")]
    public string? PurchaseStore { get; set; }

    [QueryParameter("rating")]
    public int? Rating { get; set; }

    [QueryParameter("storage_location")]
    public string? StorageLocation { get; set; }
}
