// <auto-generated>
// Generated by tools/codegen/generate_models.py from "Metron Comicbook Database.yaml".
// Do not edit by hand -- re-run the script instead.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Metron.Api.Http;

namespace Metron.Api.Filters;

public sealed class IssueFilter
{
    /// <summary>Alternate Number</summary>
    [QueryParameter("alt_number")]
    public string? AltNumber { get; set; }

    /// <summary>Character Metron ID</summary>
    [QueryParameter("character_id")]
    public int? CharacterId { get; set; }

    /// <summary>Cover Hash</summary>
    [QueryParameter("cover_hash")]
    public string? CoverHash { get; set; }

    /// <summary>Cover Month</summary>
    [QueryParameter("cover_month")]
    public double? CoverMonth { get; set; }

    /// <summary>Cover Year</summary>
    [QueryParameter("cover_year")]
    public double? CoverYear { get; set; }

    /// <summary>Creator Metron ID</summary>
    [QueryParameter("creator_id")]
    public int? CreatorId { get; set; }

    /// <summary>Comic Vine ID</summary>
    [QueryParameter("cv_id")]
    public int? CvId { get; set; }

    [QueryParameter("foc_date")]
    public DateOnly? FocDate { get; set; }

    [QueryParameter("foc_date_range_after")]
    public DateOnly? FocDateRangeAfter { get; set; }

    [QueryParameter("foc_date_range_before")]
    public DateOnly? FocDateRangeBefore { get; set; }

    /// <summary>Grand Comics Database ID</summary>
    [QueryParameter("gcd_id")]
    public int? GcdId { get; set; }

    /// <summary>Imprint Metron ID</summary>
    [QueryParameter("imprint_id")]
    public int? ImprintId { get; set; }

    /// <summary>Imprint Name</summary>
    [QueryParameter("imprint_name")]
    public string? ImprintName { get; set; }

    [QueryParameter("missing_cv_id")]
    public bool? MissingCvId { get; set; }

    [QueryParameter("missing_gcd_id")]
    public bool? MissingGcdId { get; set; }

    /// <summary>Greater than Modified DateTime</summary>
    [QueryParameter("modified_gt")]
    public DateTimeOffset? ModifiedGt { get; set; }

    /// <summary>Issue Number</summary>
    [QueryParameter("number")]
    public string? Number { get; set; }

    /// <summary>A page number within the paginated result set.</summary>
    [QueryParameter("page")]
    public int? Page { get; set; }

    /// <summary>Publisher Metron ID</summary>
    [QueryParameter("publisher_id")]
    public int? PublisherId { get; set; }

    /// <summary>Publisher Name</summary>
    [QueryParameter("publisher_name")]
    public string? PublisherName { get; set; }

    /// <summary>Rating</summary>
    [QueryParameter("rating")]
    public string? Rating { get; set; }

    /// <summary>Multiple values may be separated by commas.</summary>
    [QueryParameter("role_id")]
    public List<int>? RoleId { get; set; }

    /// <summary>Series Alternative Name</summary>
    [QueryParameter("series_alt_names")]
    public string? SeriesAltNames { get; set; }

    /// <summary>Series Metron ID</summary>
    [QueryParameter("series_id")]
    public int? SeriesId { get; set; }

    /// <summary>Series Name</summary>
    [QueryParameter("series_name")]
    public string? SeriesName { get; set; }

    /// <summary>Quick search across series name and alternative names</summary>
    [QueryParameter("series_q")]
    public string? SeriesQ { get; set; }

    /// <summary>Series Volume Number</summary>
    [QueryParameter("series_volume")]
    public int? SeriesVolume { get; set; }

    /// <summary>Series Beginning Year</summary>
    [QueryParameter("series_year_began")]
    public int? SeriesYearBegan { get; set; }

    /// <summary>Distributor SKU</summary>
    [QueryParameter("sku")]
    public string? Sku { get; set; }

    [QueryParameter("store_date")]
    public DateOnly? StoreDate { get; set; }

    [QueryParameter("store_date_range_after")]
    public DateOnly? StoreDateRangeAfter { get; set; }

    [QueryParameter("store_date_range_before")]
    public DateOnly? StoreDateRangeBefore { get; set; }

    /// <summary>Team Metron ID</summary>
    [QueryParameter("team_id")]
    public int? TeamId { get; set; }

    /// <summary>Universe Metron ID</summary>
    [QueryParameter("universe_id")]
    public int? UniverseId { get; set; }

    /// <summary>UPC Code</summary>
    [QueryParameter("upc")]
    public string? Upc { get; set; }

    /// <summary>UPC Code starts with (e.g. the 12-digit UPC-A read by a mobile scanner that strips the 5-digit EAN supplemental)</summary>
    [QueryParameter("upc_starts_with")]
    public string? UpcStartsWith { get; set; }
}
