// <auto-generated>
// Generated by tools/codegen/generate_models.py from "Metron Comicbook Database.yaml".
// Do not edit by hand -- re-run the script instead.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Metron.Api.Http;

namespace Metron.Api.Filters;

public sealed class PullListIssuesFilter
{
    /// <summary>A page number within the paginated result set.</summary>
    [QueryParameter("page")]
    public int? Page { get; set; }

    /// <summary>Return issues with a store date on or after this date (YYYY-MM-DD).</summary>
    [QueryParameter("store_date_after")]
    public string? StoreDateAfter { get; set; }

    /// <summary>Return issues with a store date on or before this date (YYYY-MM-DD).</summary>
    [QueryParameter("store_date_before")]
    public string? StoreDateBefore { get; set; }
}
