// <auto-generated>
// Generated by tools/codegen/generate_models.py from "Metron Comicbook Database.yaml".
// Do not edit by hand -- re-run the script instead.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Metron.Api.Http;

namespace Metron.Api.Filters;

public sealed class ReadingListFilter
{
    /// <summary>Source where this reading list information was obtained</summary>
    [QueryParameter("attribution_source")]
    public string? AttributionSource { get; set; }

    /// <summary>Minimum Rating</summary>
    [QueryParameter("average_rating__gte")]
    public double? AverageRatingGte { get; set; }

    [QueryParameter("is_private")]
    public bool? IsPrivate { get; set; }

    /// <summary>The type of reading list</summary>
    [QueryParameter("list_type")]
    public string? ListType { get; set; }

    /// <summary>Greater than Modified DateTime</summary>
    [QueryParameter("modified_gt")]
    public DateTimeOffset? ModifiedGt { get; set; }

    [QueryParameter("name")]
    public string? Name { get; set; }

    /// <summary>A page number within the paginated result set.</summary>
    [QueryParameter("page")]
    public int? Page { get; set; }

    /// <summary>Publisher</summary>
    [QueryParameter("publisher")]
    public string? Publisher { get; set; }

    [QueryParameter("user")]
    public int? User { get; set; }

    [QueryParameter("username")]
    public string? Username { get; set; }
}
