// <auto-generated>
// Generated by tools/codegen/generate_models.py from "Metron Comicbook Database.yaml".
// Do not edit by hand -- re-run the script instead.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Metron.Api.Http;

namespace Metron.Api.Filters;

public sealed class SeriesFilter
{
    [QueryParameter("alt_names")]
    public string? AltNames { get; set; }

    /// <summary>Character Metron ID</summary>
    [QueryParameter("character_id")]
    public int? CharacterId { get; set; }

    /// <summary>Creator Metron ID</summary>
    [QueryParameter("creator_id")]
    public int? CreatorId { get; set; }

    /// <summary>Comic Vine ID</summary>
    [QueryParameter("cv_id")]
    public int? CvId { get; set; }

    /// <summary>Grand Comics Database ID</summary>
    [QueryParameter("gcd_id")]
    public int? GcdId { get; set; }

    /// <summary>Imprint Metron ID</summary>
    [QueryParameter("imprint_id")]
    public int? ImprintId { get; set; }

    [QueryParameter("imprint_name")]
    public string? ImprintName { get; set; }

    [QueryParameter("missing_cv_id")]
    public bool? MissingCvId { get; set; }

    [QueryParameter("missing_gcd_id")]
    public bool? MissingGcdId { get; set; }

    /// <summary>Greater than Modified DateTime</summary>
    [QueryParameter("modified_gt")]
    public DateTimeOffset? ModifiedGt { get; set; }

    [QueryParameter("name")]
    public string? Name { get; set; }

    /// <summary>A page number within the paginated result set.</summary>
    [QueryParameter("page")]
    public int? Page { get; set; }

    [QueryParameter("publisher_id")]
    public int? PublisherId { get; set; }

    [QueryParameter("publisher_name")]
    public string? PublisherName { get; set; }

    /// <summary>Quick search across name and alternative names</summary>
    [QueryParameter("q")]
    public string? Q { get; set; }

    /// <summary>Multiple values may be separated by commas.</summary>
    [QueryParameter("role_id")]
    public List<int>? RoleId { get; set; }

    [QueryParameter("series_type")]
    public string? SeriesType { get; set; }

    [QueryParameter("series_type_id")]
    public int? SeriesTypeId { get; set; }

    [QueryParameter("status")]
    public int? Status { get; set; }

    /// <summary>Team Metron ID</summary>
    [QueryParameter("team_id")]
    public int? TeamId { get; set; }

    /// <summary>Universe Metron ID</summary>
    [QueryParameter("universe_id")]
    public int? UniverseId { get; set; }

    [QueryParameter("volume")]
    public int? Volume { get; set; }

    [QueryParameter("year_began")]
    public int? YearBegan { get; set; }

    [QueryParameter("year_end")]
    public int? YearEnd { get; set; }
}
