#!/usr/bin/env python3
"""Generates C# models, enums, and query filters from the Metron OpenAPI schema.

Usage: python3 tools/codegen/generate_models.py

Reads "Metron Comicbook Database.yaml" from the repo root and writes:
  src/Metron.Api/Models/Generated/*.cs   (one file per object schema, plus Enums.cs)
  src/Metron.Api/Filters/*.cs            (one file per GET-list operation)

Re-run manually whenever the schema file changes; the output is committed to the repo.

Design rules:
  - Every generated model property is nullable, regardless of the schema's `required` list.
    This keeps read/write DTOs interchangeable without constructor ceremony across ~90 schemas.
  - `Paginated*List` wrapper schemas are skipped; callers use the generic PagedResult<T> instead.
  - String enums with identifier-safe values become real C# string enums (JsonStringEnumConverter).
  - Integer enums are only generated as real C# enums when their `description` gives every value
    a distinct semantic name (e.g. StatusEnum: 1=Cancelled). Otherwise (RatingEnum, PriorityEnum)
    or when the enum is decimal-valued (DesiredGradeEnum), the property falls back to a plain
    scalar type, since decimal can't be a C# enum's underlying type anyway.
  - BlankEnum/NullEnum are drf-spectacular artifacts for nullable unions, not real enums; skipped.
  - `allOf: [$ref]` (single-ref wrapper) and `oneOf: [$ref, NullEnum|BlankEnum]` (nullable enum
    union) are both resolved down to the referenced type.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "Metron Comicbook Database.yaml"
MODELS_DIR = REPO_ROOT / "src/Metron.Api/Models/Generated"
FILTERS_DIR = REPO_ROOT / "src/Metron.Api/Filters"

HEADER = """// <auto-generated>
// Generated by tools/codegen/generate_models.py from "Metron Comicbook Database.yaml".
// Do not edit by hand -- re-run the script instead.
// </auto-generated>
#nullable enable

"""

CS_KEYWORDS = {
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
    "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
    "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
    "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
    "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
    "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
    "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
    "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
    "void", "volatile", "while",
}


def load_schema() -> dict:
    with SCHEMA_PATH.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def pascal_case(snake: str) -> str:
    parts = [p for p in re.split(r"[_\-]", snake) if p]
    return "".join(p[:1].upper() + p[1:] for p in parts) or snake


def csharp_identifier(snake: str) -> str:
    name = pascal_case(snake)
    if name and name[0].isdigit():
        name = "_" + name
    return name


def is_paginated_wrapper(name: str, schema: dict) -> bool:
    if not re.match(r"^Paginated.*List$", name):
        return False
    props = schema.get("properties", {})
    return {"count", "results"}.issubset(props.keys())


# ---------------------------------------------------------------------------
# Pass 1: classify every top-level schema.
# ---------------------------------------------------------------------------

class SchemaKind:
    SKIP = "skip"                 # BlankEnum / NullEnum / Paginated* wrapper
    STRING_ENUM = "string_enum"
    INT_ENUM = "int_enum"
    SCALAR_FALLBACK = "scalar"    # enum-like schema that collapses to a plain scalar type
    CLASS = "class"


def parse_description_names(description: str, values: list) -> dict | None:
    """Parses "* `value` - Name" lines from a schema description.

    Returns a dict value->PascalName if every value gets a distinct, non-numeric name;
    otherwise None (meaning: no real semantic names, e.g. RatingEnum's "* `1` - 1").
    """
    if not description:
        return None
    lines = {}
    for line in description.splitlines():
        m = re.match(r"\s*\*\s*`([^`]+)`\s*-\s*(.+?)\s*$", line)
        if m:
            lines[m.group(1)] = m.group(2)
    names = {}
    seen = set()
    for v in values:
        raw = lines.get(str(v))
        if raw is None:
            return None
        # A "name" that's just the numeric value itself isn't a real semantic name.
        if re.match(r"^-?\d+(\.\d+)?$", raw.strip()):
            return None
        name = csharp_identifier(re.sub(r"[^A-Za-z0-9]+", "_", raw))
        if not name or name in seen:
            return None
        seen.add(name)
        names[v] = name
    return names


def classify_schemas(schemas: dict) -> dict:
    classification = {}
    for name, schema in schemas.items():
        if name in ("BlankEnum", "NullEnum"):
            classification[name] = (SchemaKind.SKIP, None)
            continue
        if is_paginated_wrapper(name, schema):
            classification[name] = (SchemaKind.SKIP, None)
            continue
        if "enum" in schema:
            values = schema["enum"]
            stype = schema.get("type")
            if stype == "string" and all(re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", str(v)) for v in values):
                classification[name] = (SchemaKind.STRING_ENUM, None)
            elif stype == "integer":
                names = parse_description_names(schema.get("description", ""), values)
                if names is not None:
                    classification[name] = (SchemaKind.INT_ENUM, names)
                else:
                    classification[name] = (SchemaKind.SCALAR_FALLBACK, "int?")
            elif stype == "number":
                classification[name] = (SchemaKind.SCALAR_FALLBACK, "decimal?")
            else:
                classification[name] = (SchemaKind.SCALAR_FALLBACK, "string?")
            continue
        classification[name] = (SchemaKind.CLASS, None)
    return classification


# ---------------------------------------------------------------------------
# Pass 2: property type resolution.
# ---------------------------------------------------------------------------

def resolve_ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def csharp_type_for(schema: dict, classification: dict) -> tuple[str, str | None]:
    """Returns (csharp_type, converter_attribute_or_None)."""
    if "allOf" in schema and len(schema["allOf"]) == 1 and "$ref" in schema["allOf"][0]:
        return csharp_type_for(schema["allOf"][0], classification)

    if "oneOf" in schema:
        real_ref = None
        for opt in schema["oneOf"]:
            if "$ref" in opt and resolve_ref_name(opt["$ref"]) not in ("BlankEnum", "NullEnum"):
                real_ref = opt
        if real_ref is not None:
            return csharp_type_for(real_ref, classification)
        return "string?", None

    if "$ref" in schema:
        ref_name = resolve_ref_name(schema["$ref"])
        kind, extra = classification.get(ref_name, (SchemaKind.CLASS, None))
        if kind == SchemaKind.SCALAR_FALLBACK:
            return extra, None
        if kind in (SchemaKind.STRING_ENUM, SchemaKind.INT_ENUM):
            return ref_name + "?", None
        if kind == SchemaKind.SKIP:
            return "object?", None
        return ref_name + "?", None

    stype = schema.get("type")
    sformat = schema.get("format")

    if stype == "array":
        items = schema.get("items", {})
        item_type, item_conv = csharp_type_for(items, classification)
        if item_type.endswith("?"):
            item_type = item_type[:-1]
        return f"List<{item_type}>?", item_conv

    if stype == "integer":
        return "int?", None
    if stype == "number":
        if sformat == "decimal":
            return "decimal?", "DecimalStringConverter"
        return "double?", None
    if stype == "boolean":
        return "bool?", None
    if stype == "string":
        if sformat == "date":
            return "DateOnly?", None
        if sformat == "date-time":
            return "DateTimeOffset?", None
        if sformat == "decimal":
            return "decimal?", "DecimalStringConverter"
        return "string?", None
    if stype == "object":
        return "Dictionary<string, object>?", None

    return "string?", None


def render_class(name: str, schema: dict, classification: dict) -> str:
    lines = [HEADER.rstrip("\n"), "", "using System;", "using System.Collections.Generic;",
             "using System.Text.Json.Serialization;", "using Metron.Api.Serialization;", "",
             "namespace Metron.Api.Models;", ""]
    desc = schema.get("description")
    if desc:
        lines.append("/// <summary>")
        for line in desc.splitlines():
            lines.append(f"/// {line}")
        lines.append("/// </summary>")
    lines.append(f"public sealed class {name}")
    lines.append("{")
    props = schema.get("properties", {})
    used_names: set[str] = set()
    for prop_name, prop_schema in props.items():
        cs_type, converter = csharp_type_for(prop_schema, classification)
        cs_name = csharp_identifier(prop_name)
        if cs_name == name:
            # A property can't share its enclosing class's name in C#.
            cs_name += "Value"
        if cs_name in used_names:
            continue
        used_names.add(cs_name)
        title = prop_schema.get("title") or prop_schema.get("description")
        if title:
            lines.append(f"    /// <summary>{title.splitlines()[0]}</summary>")
        lines.append(f'    [JsonPropertyName("{prop_name}")]')
        if converter:
            lines.append(f"    [JsonConverter(typeof({converter}))]")
        lines.append(f"    public {cs_type} {cs_name} {{ get; set; }}")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def render_enums_file(classification: dict, schemas: dict) -> str:
    lines = [HEADER.rstrip("\n"), "", "using System.Text.Json.Serialization;", "",
             "namespace Metron.Api.Models;", ""]
    for name, (kind, extra) in classification.items():
        schema = schemas[name]
        if kind == SchemaKind.STRING_ENUM:
            desc = schema.get("description")
            if desc:
                lines.append("/// <summary>")
                for line in desc.splitlines():
                    lines.append(f"/// {line}")
                lines.append("/// </summary>")
            lines.append("[JsonConverter(typeof(JsonStringEnumConverter))]")
            lines.append(f"public enum {name}")
            lines.append("{")
            for v in schema["enum"]:
                member = csharp_identifier(str(v))
                if member in CS_KEYWORDS or (member and member[0].isdigit()):
                    member = "_" + member
                lines.append(f"    {member},")
            lines.append("}")
            lines.append("")
        elif kind == SchemaKind.INT_ENUM:
            lines.append(f"public enum {name}")
            lines.append("{")
            for v in schema["enum"]:
                lines.append(f"    {extra[v]} = {v},")
            lines.append("}")
            lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Filters: derived from GET *_list operations' query parameters.
# ---------------------------------------------------------------------------

def filter_class_name(operation_id: str) -> str:
    op = operation_id
    if op.startswith("api_"):
        op = op[len("api_"):]
    if op.endswith("_list"):
        op = op[: -len("_list")]
    return pascal_case(op) + "Filter"


def param_csharp_type(param_schema: dict, style_array: bool) -> str:
    stype = param_schema.get("type")
    sformat = param_schema.get("format")
    if stype == "array":
        item_type = param_schema.get("items", {}).get("type", "string")
        base = {"integer": "int", "string": "string", "number": "double", "boolean": "bool"}.get(item_type, "string")
        return f"List<{base}>?"
    if stype == "integer":
        return "int?"
    if stype == "number":
        return "double?"
    if stype == "boolean":
        return "bool?"
    if stype == "string":
        if sformat == "date":
            return "DateOnly?"
        if sformat == "date-time":
            return "DateTimeOffset?"
        return "string?"
    return "string?"


def render_filter_class(class_name: str, params: list) -> str:
    lines = [HEADER.rstrip("\n"), "", "using System;", "using System.Collections.Generic;",
             "using Metron.Api.Http;", "", "namespace Metron.Api.Filters;", "",
             f"public sealed class {class_name}", "{"]
    seen = set()
    for p in params:
        pname = p["name"]
        if pname in seen:
            continue
        seen.add(pname)
        cs_type = param_csharp_type(p.get("schema", {}), False)
        cs_name = csharp_identifier(pname)
        desc = p.get("description")
        if desc:
            lines.append(f"    /// <summary>{desc.splitlines()[0]}</summary>")
        lines.append(f'    [QueryParameter("{pname}")]')
        lines.append(f"    public {cs_type} {cs_name} {{ get; set; }}")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_filters(spec: dict) -> dict[str, str]:
    files = {}
    for path, path_item in spec.get("paths", {}).items():
        get_op = path_item.get("get")
        if not get_op:
            continue
        op_id = get_op.get("operationId", "")
        if not op_id.endswith("_list"):
            continue
        query_params = [p for p in get_op.get("parameters", []) if p.get("in") == "query"]
        if not query_params:
            continue
        class_name = filter_class_name(op_id)
        files[class_name] = render_filter_class(class_name, query_params)
    return files


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    spec = load_schema()
    schemas = spec["components"]["schemas"]
    classification = classify_schemas(schemas)

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    FILTERS_DIR.mkdir(parents=True, exist_ok=True)
    for f in MODELS_DIR.glob("*.cs"):
        f.unlink()
    for f in FILTERS_DIR.glob("*.cs"):
        f.unlink()

    class_count = 0
    for name, schema in schemas.items():
        kind, _ = classification[name]
        if kind == SchemaKind.CLASS:
            (MODELS_DIR / f"{name}.cs").write_text(render_class(name, schema, classification), encoding="utf-8")
            class_count += 1

    (MODELS_DIR / "Enums.cs").write_text(render_enums_file(classification, schemas), encoding="utf-8")

    filters = generate_filters(spec)
    for class_name, content in filters.items():
        (FILTERS_DIR / f"{class_name}.cs").write_text(content, encoding="utf-8")

    print(f"Generated {class_count} model classes, "
          f"{sum(1 for k,_ in classification.values() if k in (SchemaKind.STRING_ENUM, SchemaKind.INT_ENUM))} enums, "
          f"{len(filters)} filter classes.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
